apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PPM
  description: |
    Project and Portfolio Management (PPM) is a global application tool catering to IT Portfolio Management, Governance, Security and Compliance aspects as well is a “Single Source of Truth” for all IT Services across Enterprise IT
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: Application
  owner: gfgo
  lifecycle: production
